import 'package:floor/floor.dart';

/// Represents a customer entity in the database.
///
/// This class defines the structure of a customer record with fields
/// for customer ID, first name, last name, address, and birthday.
@Entity(tableName: 'Customer')
class Customer {
  /// The unique identifier for the customer.
  ///
  /// This field is the primary key for the `Customer` table and is
  /// auto-generated by the database.
  @PrimaryKey(autoGenerate: true)
  final int? customerID;

  /// The first name of the customer.
  final String firstName;

  /// The last name of the customer.
  final String lastName;

  /// The address of the customer.
  final String address;

  /// The birthday of the customer in a string format.
  final String birthday;

  /// Creates a new [Customer] instance.
  ///
  /// The [customerID] is optional and will be auto-generated if not provided.
  /// The [firstName], [lastName], [address], and [birthday] parameters are required.
  Customer(this.firstName, this.lastName, this.address, this.birthday, {this.customerID});
}
